### ISSUE TITLE
Failed to setup (Access is denied. )

### ISSUE THREAD

**Issue by RoychenHKMU** [uav4geo/OpenPointClass#23]
i am following the instructions to install. when i use the command 

"cmake [-DWITH_GBT=ON] -DCMAKE_TOOLCHAIN_FILE=<C:\Researchteam\vcpkg\vcpkg>/scripts/buildsystems/vcpkg.cmake .."

it show "Access is denied." I already using administrator to open anaconda prompt, please someone help thank you so much.

**Comment by pierotofy** [comment]
I'm not really sure, but I don't think it's a problem with OpenPointClass?
